### ISSUE TITLE
Astropad Standard: Error running recipes

### ISSUE THREAD

**Issue by beatlemike** [autopkg/jazzace-recipes#11]
Latest version of Astropad Standard gets error during download:

> Unarchiving /Users/tsc/Library/AutoPkg/Cache/local.download.AstropadStandard/downloads/Astropad-3.2.zip with ditto failed: ditto: Couldn't read PKZip signature

**Comment by beatlemike** [comment]
It's apparently a DMG now, not a zip

**Comment by jazzace** [comment]
Yeah, the zip version is still available, but it is not current. Pull request #12 by @blackthroat will solve this, but child recipes will need to change.

**Comment by jazzace** [comment]
Solved by PR #12
