### ISSUE TITLE
Vectorworks.download.recipe fails for 2021 recipes

### ISSUE THREAD

**Issue by KWik** [autopkg/jazzace-recipes#19]
Vectorworks.download.recipe fails for 2021 recipes since the recipe wants the identifier
net.nemetschek.2021.vectorworksinstaller
while the 2021 is
net.vectorworks.2021.vectorworksinstaller

**Comment by jazzace** [comment]
I have updated the download recipe to reflect that change (and one other), making the default values correct for 2021. Users who want to run 2020 should use the new 2020 recipes. Users with existing overrides should only need to change the year number and the URL for their locale.
