### ISSUE TITLE
com.github.jazzace.pkg.MeshLab failed

### ISSUE THREAD

**Issue by magnusviri** [autopkg/jazzace-recipes#25]
When I run com.github.jazzace.pkg.MeshLab I get this error.

	> autopkg run com.github.jazzace.pkg.MeshLab
	Processing com.github.jazzace.pkg.MeshLab...
	/AutoPkg/Cache/com.github.jazzace.pkg.MeshLab/downloads/MeshLab.dmg is not mounted
	Failed.

	The following recipes failed:
		com.github.jazzace.pkg.MeshLab
			Error in com.github.jazzace.pkg.MeshLab: Processor: AppPkgCreator: Error: /AutoPkg/Cache/com.github.jazzace.pkg.MeshLab/downloads/MeshLab.dmg is not mounted

	The following new items were downloaded:
		Download Path                                                        
		-------------                                                        
		/AutoPkg/Cache/com.github.jazzace.pkg.MeshLab/downloads/MeshLab.dmg

**Comment by jazzace** [comment]
For future reference, providing a verbose run (`autopkg run -vv`), with sensitive info redacted, is helpful in determining where the error occurred.

In this case, I did a verbose run and found out that the parent download recipe is incorrectly grabbing the Linux version. The download recipe that my recipe calls is from the hansen-m-recipes repo. Please file this issue there.
