### ISSUE TITLE
MuseScore download failing

### ISSUE THREAD

**Issue by eshirk** [autopkg/jazzace-recipes#29]
The MuseScore download recipe is failing on the new v4.0 release. If I'm understanding what I'm seeing in the Sparkle feed correctly, only the Muse_Hub.dmg is available for download there; for MuseScore.dmg, we're supposed to use https://musescore.org/en/download/musescore.dmg.

**Comment by jazzace** [comment]
Thanks for reporting this. That link has at least 2 redirects, so I will have to do some testing to see if it will work in an AutoPkg context. The Sparkle framework is still there but I can't determine the feed yet.

**Comment by eshirk** [comment]
It was this bit from the Sparkle page that made me think there might not be a Sparkle feed for the v4 download without Muse Hub:
<p>We recommend visiting <a href="https://www.musescore.org"> www.musescore.org</a> to install MuseScore 4.</p>

**Comment by jazzace** [comment]
I saw that as well, but they did not eliminate Sparkle from the app bundle.

**Comment by paul-cossey** [comment]
Almost the end of the day here in the UK, but I found the following after running `strings` on the binary. Might be able to piece a working feed url together using this?

```
External
update
musescore://update/releaseinfo
MuseScore/Update/ReleaseInfoDialog.qml
musescore://update
MuseScore/Update/UpdateProgressDialog.qml
MuseScore.Update
UpdateModel
/Users/runner/work/MuseScore/MuseScore/src/update/qml
application/checkForUpdate
application/checkForUpdateTestingMode
application/skippedVersion
/about/desktop-privacy-policy
https://updates.musescore.org/feed/latest.xml
https://updates.musescore.org/feed/latest.test.xml
/update
You already have the latest version of MuseScore. Please visit <a href="%1">musescore.org</a> for news on what's coming next.
re up to date!
title=
notes=
musescore://update/releaseinfo?%1
void mu::update::UpdateScenario::showReleaseInfo(const mu::update::ReleaseInfo &)
install
remindLater
skip
Cannot connect to server
Sorry - please try again later
musescore://update?mode=download
MuseScore needs to close to complete the installation. If you have any unsaved changes, you will be prompted to save them before MuseScore closes.
Close
mu::RetVal<ReleaseInfo> mu::update::UpdateService::parseRelease(const QByteArray &) const
body
tag_name
assets
browser_download_url
Check for &update
Updating MuseScore
Musescore/%1 (%2 %3; %4)
IUpdateService
notes
fileUrl
IUpdateScenario
auto mu::update::UpdateScenario::doCheckForUpdate(bool)::(anonymous class)::operator()(const mu::framework::ProgressResult &) const
Unable to check for update, error: 
map::at:  key not found
Downloading MuseScore
auto mu::update::UpdateModel::load(const QString &)::(anonymous class)::operator()(const mu::framework::ProgressResult &) const
download
```

**Comment by paul-cossey** [comment]
At a guess, I'd say that this will be the sparkle feed url https://updates.musescore.org/feed/latest.xml 

But seeing as it's new, and there aren't any version 4 updates nothings been published to the feed yet.

```
curl https://updates.musescore.org/feed/latest.xml
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by jazzace** [comment]
I decided to scrape the download page for the direct link to the download of the current version using URLTextSearcher. Should a Sparkle feed arise later, I can change it back. But the version I just posted works with my recipe chains. Thanks to all for your contributions.
