### ISSUE TITLE
KeyShot.download.recipe failes with "Error: No match found on URL"

### ISSUE THREAD

**Issue by macbofh** [autopkg/jazzace-recipes#33]
It looks like the download URL changed because running the KeyShot.download.recipe failes with the message:

```No match found on URL: https://www.keyshot.com/resources/downloads/
Failed.

The following recipes failed:
    /Users/autopkg/Documents/autopkg/RecipeRepos/com.github.autopkg.jazzace-recipes/Luxion/KeyShot.download.recipe
        Error in com.github.jazzace.download.keyshot: Processor: URLTextSearcher: Error: No match found on URL: https://www.keyshot.com/resources/downloads/

Nothing downloaded, packaged or imported.
```

The download url for the latest package on the download site is:
https://download.keyshot.com/keyshot2023/keyshot_mac64_2023.1_12.0.0.186.pkg

**Comment by jazzace** [comment]
Thanks for the report (and the nudge to get it fixed). I've changed the regex in the download URL to fetch the latest version in [the latest commit](https://github.com/autopkg/jazzace-recipes/commit/8c385a25344785d0d89e1e471f9fd423d2355924).

**Comment by macbofh** [comment]
They changed the download URL's again.

The main download url and redirect is
https://www.keyshot.com/download/357619/

The direct pkg link for the latest version is https://download.keyshot.com/keyshot2023/keyshot_mac64_2023.3_12.2.2.4.pkg

**Comment by jazzace** [comment]
This is a different issue than the previous one. Luxion has protected the download for the current version behind a login wall. The current version appears to be 2024.1. I doubt I will be able to fix this. Expect the recipe to be removed in the near future.

**Comment by macbofh** [comment]
The direct download links are not behind a login wall, just the overview to the main download page where you can find the links is behind a login wall. After storing the direct download link, you will not need to login anymore.

For keyshot2023 the direct downloadlink and forward to the latest package is
https://www.keyshot.com/download/357619/

For keyshot2024 the direct downloadlink and forward to the latest package is
https://www.keyshot.com/download/370762/

I understand that i will only be a matter of time that Luxion will also put the download links behind a login wall. (But for now these links still work)

**Comment by jazzace** [comment]
Can you show me where those links are posted publicly? The recipe needs a public page to be able to determine the latest version. I've found the page for 2023 and earlier but as I was trying to communicate, the page with the download link for the current version is protected by a login wall (the download itself is not).

**Comment by jazzace** [comment]
I've worked around the problem by having the user enter the 6-digit download number from the link as an input variable (PRODUCT_ID) to determine which version of KeyShot to download ([commit details](https://github.com/autopkg/jazzace-recipes/commit/4644c4a02827e254b5e240bc7d704007dc23155b)). This will be the final update I make to this recipe, as we will no longer be using KeyShot (11) as of July, but it should work for quite a while, assuming Luxion doesn't change their download redirect scheme again.

**Comment by paul-cossey** [comment]
Thanks for your work on these, @jazzace and @macbofh. 

Do we know for sure that it's a Product ID, and not a random folder name generated at release? 

We have some recipes for KeyShot Network Rendering I'd like to fix using the same method if possible.

**Comment by jazzace** [comment]
I checked in the Internet Archive and it does seem that it is a Product ID. That is, I can confirm that earlier versions of KeyShot 11 and 2023 used the same redirect link as the most recent releases, so that 6-digit number seems to be consistent within major versions.

**Comment by paul-cossey** [comment]
Awesome! Thank you 😄

**Comment by macbofh** [comment]
Great, Thanks @jazzace !!
