### ISSUE TITLE
KeyShot.download.recipe failes with "No match found on URL"

### ISSUE THREAD

**Issue by johndvries** [autopkg/jazzace-recipes#35]
It looks like the download URL changed because running the KeyShot.download.recipe failes with the message:

The following recipes failed:
    /Users/autopkg/Documents/autopkg/RecipeRepos/com.github.autopkg.jazzace-recipes/Luxion/KeyShot.download.recipe
        Error in com.github.jazzace.download.keyshot: Processor: URLTextSearcher: Error: No match found on URL: https://www.keyshot.com/resources/downloads/

Nothing downloaded, packaged or imported.

The download url for the latest package on the download site is:
https://www.keyshot.com/download/357619/?tmstv=1687817414

**Comment by jazzace** [comment]
This is the second time they've changed the URL scheme on that page for this major version (they added a redirect this time). I am not convinced that the 6-digit number in the URL will be static. Let me see if I can come up with something a little more robust.

**Comment by jazzace** [comment]
I've posted a fix. (As it turned out, Elliot's fix would have worked because the 6-digit number appears to be a product number, but this recipe should continue working with the next major version (assuming the download page doesn't change yet again).
