### ISSUE TITLE
Vectorworks2024 download recipes fails

### ISSUE THREAD

**Issue by vmiller** [autopkg/jazzace-recipes#38]
URLDownloader is failing with an error.  Sample run : 

`autopkg run -v Vectorworks2024.download
Processing Vectorworks2024.download...
WARNING: Vectorworks2024.download is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLDownloader
URLDownloader: ERROR: (28) Operation too slow. Less than 1 bytes/sec transferred the last 30 seconds

curl: (28) Operation too slow. Less than 1 bytes/sec transferred the last 30 seconds

Failed.
Receipt written to /Users/millerva/Library/AutoPkg/Cache/com.github.jazzace.download.vectorworks2024/receipts/Vectorworks2024-receipt-20241206-152800.plist

The following recipes failed:
    Vectorworks2024.download
        Error in com.github.jazzace.download.vectorworks2024: Processor: URLDownloader: Error: curl: (28) Operation too slow. Less than 1 bytes/sec transferred the last 30 seconds

Nothing downloaded, packaged or imported.`

The URL https://release.vectorworks.net/latest/Vectorworks/2024-NNA-eng-mac works when I visit in a browser, but I have been unable to get it to work with curl from the command line.

**Comment by jazzace** [comment]
I just tested it and it worked fine for me (although it did take 5 minutes for the download). Try again and see if it was a temporary issue.

**Comment by vmiller** [comment]
Interesting.

I've tried it on 2 different computers on 2 different networks since yesterday with the same results.  Just tried it again now to be sure, and get the same failure.

**Comment by jazzace** [comment]
Can you try the recipe for 2025 (VectorworksInstallManager.download) to see if you get the same problem?

**Comment by vmiller** [comment]
That one worked for me

**Comment by jazzace** [comment]
OK, that download is a lot smaller but from the same host. So unless that one took 5 minutes to download, it shouldn't be that Nemetschek has throttled your IP range. I just tested the 2024 recipe on a different computer and got it in less than 2 minutes. I'm guessing the issue is on the server end, but let's circle back next week to see if it persists for you.

**Comment by vmiller** [comment]
To follow up on this, I realized my machines we running autopkg 2.7.2.   I updated them to 2.7.3 and not this recipe works as expected.   Just for completeness, I tossed 2.7.2 on a clean test machine and duplicated the error.
