### ISSUE TITLE
Desire to keep .ds recipes alive?

### ISSUE THREAD

**Issue by homebysix** [autopkg/jazzace-recipes#42]
This repo's readme includes this helpful context:

> .ds recipes can still be used to copy a package installer without version information in the filename to a local directory. One possible application would be to keep the installers you use in [MDS](https://twocanoes.com/products/mac/mac-deploy-stick/) up to date.

Do you have any interest in keeping these .ds recipes going for the above reason, or do you think it's time to add DeprecationWarning to them and let them expire?

On one hand, the .ds type is probably the closest thing AutoPkg has to a standard "copy files into this directory" recipe for non-Munki users. On the other hand, I suspect the number of people still using these recipes in production is low, and maintenance effort isn't zero.

Interested in your thoughts! If you want to deprecate them, I can make a PR easily.

**Comment by jazzace** [comment]
Not interested in deprecating at this time. I still have an MDS setup for the few Intel Macs I have left. I suspect I will deprecate when those Intel Macs go out of production or when I retire, whichever comes first.
