### ISSUE TITLE
Ableton live packs

### ISSUE THREAD

**Issue by geoffklee** [autopkg/jazzace-recipes#7]
Hi, wondering if you've found a solution for dealing with Live packs? They come in a custom format, and when installed they write a bunch of files to one location, and a line in the general prefs file. I'm having trouble thinking of a satisfying way to package these and I'd appreciate your thoughts!

**Comment by jazzace** [comment]
We're just dipping our toes into Live right now (only installing the Lite version that was licensed with our MIDI Keyboards), so I have zero experience with Live packs. I suggest asking in the #musicsupport channel of the MacAdmins Slack.
